### ISSUE TITLE
add possible argument options for tasks

### ISSUE THREAD

**Issue by smokingplaya** [smokingplaya/puff#8]
example
```yaml
tasks:
  default:
    arguments:
      - name: test
        choices: ["hi", "goodbye"]
```
