### ISSUE TITLE
add a keyword to wait for threads to stop

### ISSUE THREAD

**Issue by smokingplaya** [smokingplaya/puff#9]
example:
```yaml
commands:
  - thread: gcc ...
  - wait: echo "builded"
```
